FROM node:20-alpine3.20
RUN apk upgrade --no-cache
WORKDIR /src
COPY package*.json ./
RUN npm install
COPY . .

# Expose the default Vite port (5173) or CRA port (3000)
EXPOSE 8080
CMD ["npm", "start"]